services:
    db:
        image: mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "Y"
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8090:80
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db

    angular:
        build:
            context: ./Web_AddicTrack
            dockerfile: DockerFile
        ports:
            - 8080:80

    api:
        build:
            context: ./Back_AddicTrack
            dockerfile: Dockerfile
        environment:
            DefaultConnection: "server=db;port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}"  
        ports:
            - 8081:8080
        depends_on:
            - db

volumes:
    db-data:
