services:
    nginx:
      image: nginx
      ports:
      - 8091:80
      volumes:
      - ./DevOps/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./DevOps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./DevOps/nginx/logs/:/var/log/nginx

    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"

    phpmyadmin:
        image: phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db

    angular:
        build:
            context: ./Web_AddicTrack
            dockerfile: DockerFile
        ports:
        - "4200:80"
