FROM node:18 AS build

WORKDIR /app

COPY . .

RUN npm ci
RUN npm run build

FROM nginx:latest

COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/addic-track/browser /usr/share/nginx/html
