FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build --prod

FROM nginx:alpine

COPY ./docker/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/fabrique_papier /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]