FROM node:18 AS builder

EXPOSE 80
EXPOSE 4200

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build --prod

FROM nginx:alpine

#COPY ./docker/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/addic-track /usr/share/nginx/html

EXPOSE 80
EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]